DATA:
  num_class: 6
  modality: RGB
  test_list: /workspace/mnt/group/algorithm/kanghaidong/video_project/Video1.0_list_file/bk-video-list-V1.0-a-val.txt
  input_type: video
  video_handler: cv2
MODEL:
  arch: resnet50
  num_segments: 25
  consenus_type: avg
  resume: /workspace/mnt/group/algorithm/kanghaidong/video_project/Alg-VideoAlgorithm-dev/video-classification/tsn-pytorch/resnet50_80e_69.98p.pth.tar

